In [1]:
# %pip install numpy

In [2]:
import numpy as np

In [3]:
!pwd

/Users/miguelcamargorojas/Documents/UP/PDI - Ene-may25/Semana II


In [11]:
x = np.arange(15, dtype=np.int64).reshape(3, 5)

In [12]:
type(x)

numpy.ndarray

In [13]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
x[1, 1]

np.int64(6)

In [19]:
x[:2, :2]

array([[0, 1],
       [5, 6]])

In [21]:
x[1, 1] = 100

In [22]:
x

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [23]:
type(x)

numpy.ndarray

In [26]:
x.shape

(3, 5)

In [27]:
x.dtype

dtype('int64')

In [32]:
lista = [1, 1.1, "s", True]

In [33]:
np.asarray(lista)

array(['1', '1.1', 's', 'True'], dtype='<U32')

In [35]:
arr1 = np.asarray([1, 2, 3, 5, 6])

In [36]:
type(arr1)

numpy.ndarray

In [37]:
arr1.shape

(5,)

In [38]:
type(())

tuple

In [39]:
type((1))

int

In [40]:
type((1,))

tuple

In [42]:
# matrix 3x3

np.asarray([
    [1, 2, 3], 
    [4, 5, 6]
    ])

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.random.randint(100, size=(1000, 1000))

array([[12, 44, 45, ..., 59, 87, 81],
       [27,  9, 40, ..., 75, 56, 91],
       [35, 90, 83, ..., 85, 74, 11],
       ...,
       [60, 34, 70, ..., 56, 47, 86],
       [58, 83, 58, ..., 94, 86, 71],
       [85, 19, 50, ..., 10, 84, 14]], shape=(1000, 1000))

In [54]:
np.random.seed(32)

In [57]:
np.random.randint(100, size=(10, 10))

array([[50, 86, 38, 39,  4,  0, 16, 74, 93, 79],
       [26, 85, 41, 22, 96, 37, 92, 24, 72, 32],
       [34, 27, 43, 53, 62,  4, 21, 47, 24, 93],
       [96,  2, 79, 80,  2,  1, 40, 61, 39, 57],
       [82, 47, 25, 88, 64, 91,  5, 30, 32, 46],
       [22, 33, 98, 76,  3, 22, 26, 30, 77, 87],
       [84,  7,  0,  4, 13, 51, 15, 32, 49,  2],
       [70, 97, 75, 52, 79, 85, 25, 53, 11, 25],
       [25, 79, 92, 81, 24, 30, 47, 76, 21, 82],
       [32, 56, 39, 27, 73, 85, 11, 42, 88, 41]])