In [1]:
import numpy as np

In [2]:
np.random.seed(3)

In [3]:
a = np.random.randint(11, size=(3, 3))
b = np.random.randint(11, size=(3, 3))

In [4]:
a

array([[10,  8,  9],
       [ 3,  8,  8],
       [ 0,  5,  3]])

In [5]:
b

array([[10,  9,  9],
       [10,  5,  7],
       [ 6,  0,  4]])

In [6]:
a + b

array([[20, 17, 18],
       [13, 13, 15],
       [ 6,  5,  7]])

In [7]:
a - b

array([[ 0, -1,  0],
       [-7,  3,  1],
       [-6,  5, -1]])

In [8]:
"""
A (3, 3)
B (3, 3)
C (m, n) | Se puede llevar a cabo: Sí | El tamaño destino: 3x3 
"""
c = a * b # Producto de Hadamard

In [9]:
c.shape

(3, 3)

In [10]:
c[0, 0]

np.int64(100)

In [11]:
c

array([[100,  72,  81],
       [ 30,  40,  56],
       [  0,   0,  12]])

In [16]:
# ESTO NO SE HACE
a.__mul__(b)

array([[100,  72,  81],
       [ 30,  40,  56],
       [  0,   0,  12]])

In [17]:
# ESTO NO SE HACE
a.__matmul__(b)

array([[234, 130, 182],
       [158,  67, 115],
       [ 68,  25,  47]])

In [18]:
# Esto SÍ se hace
a @ b

array([[234, 130, 182],
       [158,  67, 115],
       [ 68,  25,  47]])

In [21]:
d = np.random.randint(101, size=(10, 13))

In [22]:
d

array([[72, 26, 24, 20, 62, 44, 30, 17, 32, 53, 86, 39, 60],
       [95, 32, 87, 88, 33, 85, 51, 90, 79, 92, 11, 17, 51],
       [71, 13, 95, 68, 94, 63, 41, 13, 77, 96, 88, 60, 47],
       [36, 55, 56, 85, 70, 87, 92, 12, 28, 10, 11, 35, 85],
       [92, 49, 72, 89, 34, 11, 89, 89, 59,  4, 85, 93,  0],
       [56, 94, 45, 71, 97, 98, 21, 34, 29, 42,  7, 94, 30],
       [76, 75, 39, 57, 49, 44, 21, 94, 41, 71, 92, 34, 15],
       [22, 45, 36, 40, 90, 52,  9, 19, 69, 54, 12, 26, 35],
       [24, 52, 98, 43, 23, 50, 18, 64, 71, 90, 53, 32, 78],
       [83, 26,  3, 37, 21, 23, 76, 18, 34, 92,  6, 70, 19]])

In [23]:
d.max()

np.int64(98)

In [24]:
d.max(axis=0) # axis=0 pregunta x columna

array([95, 94, 98, 89, 97, 98, 92, 94, 79, 96, 92, 94, 85])

In [25]:
d.max(axis=1) # axis=1 pregunta x fila

array([86, 95, 96, 92, 93, 98, 94, 90, 98, 92])

In [26]:
d.min()

np.int64(0)

In [27]:
d.min(axis=0)

array([22, 13,  3, 20, 21, 11,  9, 12, 28,  4,  6, 17,  0])

In [28]:
d.min(axis=1)

array([17, 11, 13, 10,  0,  7, 15,  9, 18,  3])

In [29]:
d.mean()

np.float64(52.06923076923077)

In [30]:
d.mean(axis=0)

array([62.7, 46.7, 55.5, 59.8, 57.3, 55.7, 44.8, 45. , 51.9, 60.4, 45.1,
       50. , 42. ])

In [31]:
d.mean(axis=1)

array([43.46153846, 62.38461538, 63.53846154, 50.92307692, 58.92307692,
       55.23076923, 54.46153846, 39.15384615, 53.53846154, 39.07692308])